name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: CocoaPods Cache
        uses: actions/cache@v3
        with:
          path: "Pods"
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Setup Project
        run: |
          pod --version
          isNeedsPodInstall=false
          diff "Podfile.lock" "Pods/Manifest.lock" >/dev/null || {
            isNeedsPodInstall=true
          }
          if $isNeedsPodInstall; then
            pod install || {
              echo "pod install fails, try update repo"
              pod install --repo-update
            }
          else
            echo "Podfile unchanged, skip pod install."
          fi

      - name: Run Tests
        run: |
          fastlane test
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.XC_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.XC_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.XC_KEY_PRIVATE }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.FASTLANE_MATCH_GIT_AUTH }}
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASS }}
